### ISSUE TITLE
Delete tmp files

### ISSUE THREAD

**Issue by steffo** [xebialabs/xlr-kubernetes-plugin#3]
We have an issue with a lot of tmp files left by the k8s plugin. 

I noticed the default setting of overthere is changed:
options.set("tmpDeleteOnDisconnect",false);

What is the reason for this?

**Comment by hierynomus** [comment]
Hi Steven,

Where do you see that being changed? That feels wrong indeed ☺

Regards,
Jeroen

**Comment by steffo** [comment]
Hi Jeroen,

It's in RemoteScript line 91

**Comment by xkapil** [comment]
Fixed. Here's the [PR](https://github.com/xebialabs/xlr-kubernetes-plugin/pull/4). Will be released as 7.5 in some time
